### ISSUE TITLE
SyntaxError: Unexpected token %

### ISSUE THREAD

**Issue by nilesh-parab** [davidmarkclements/flatstr#5]
Hi,
We are using [Pino](https://github.com/pinojs/pino) logger on our app which recently started producing error while printing logs. It internally uses flatstr for printing logs.

And it seems the last [commit](https://github.com/davidmarkclements/flatstr/commit/be4a7f3b1133cd1748bc292891fb761dd8e94870) is causing this due. The issue is due to % character before FlattenString call.

I locally overrode the package & added some console logs in catch blocks to see how its flowing. I tried to simulate this locally using below & was able to replicate that:
This is my main file (index.js)
```
var flt = require('./flatstr');
var str = 111;
console.log('the str - ', str);
var flattened = flt(str);
console.log('the flat str - ', flattened);
```

& changed the module's index.js as below:
```
'use strict'

try { 
  var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
} catch (e) {
	console.log('error1 ', e);
  try { 
    var v8 = require('v' + '8')
    v8.setFlagsFromString('--allow-natives-syntax')
    var flatstr = Function('s', 'return typeof s === "string" ? %FlattenString(s) : s')
    v8.setFlagsFromString('--no-allow-natives-syntax')
  } catch (e) {
	  console.log('error2 ', e);
    var flatstr = function flatstr(s) {
      Number(s)
      return s
    }
  }
}

module.exports = flatstr
```
Eventually the code falls back to last catch block where it just runs `Number(s)`.

The output I see after running is below:
```
C:\v8test>node index.js
error1  SyntaxError: Unexpected token %
    at Function (<anonymous>)
    at Object.<anonymous> (C:\v8test\flatstr\index.js:4:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\v8test\index.js:1:73)
the str -  111
the flat str -  111

C:\v8test>
```

When I removed the % it worked without any exceptions. Can you please help?

Thanks,
Nilesh

**Comment by davidmarkclements** [comment]
@nilesh-parab this is expected behaviour - except the part where you're actually seeing errors.

Can you clarify - your app isn't crashing is it? 

What version of Node are you using btw?

**Comment by WarmVissarutRonaldoDude** [comment]
@davidmarkclements I'm facing this issues also on node 6.9.4 && 8.9.0
btw seem like it throw `Unexpected token %` outside of this lib <try..catch> scope but not everytime seem it's happened sometime.

This is last 2 line on stack trace which cause error : https://github.com/pinojs/pino/blob/2a3857999b27e4f9436ea1d4505ffa6b882b019f/pino.js#L222
https://github.com/pinojs/pino/blob/2a3857999b27e4f9436ea1d4505ffa6b882b019f/lib/tools.js#L93

`
"error":"SyntaxError","code":500,"stack":"SyntaxError: Unexpected token %\n    at EventEmitter.pinoWrite (/var/xxx/node_modules/pino/pino.js:222:18)\n    at EventEmitter.LOG (/var/xxx/node_modules/pino/lib/tools.js:93:10)\n
`

**Comment by davidmarkclements** [comment]
@WarmVissarutRonaldoDude are you able to try it on Node 10 and node 8.11.2?

**Comment by davidmarkclements** [comment]
@WarmVissarutRonaldoDude  I'm struggling to reproduce this error

It seems that it's caught because it's being logged, so I'm assuming this isn't crashing the service

I need more details, what framework are you using, are you using the pino integration lib for that framework (e.g. hapi-pino, express-pino-logger etc) .. are you using the cluster module, are you using an uncaughtException handler.. 

is there any way you can show me your code?

**Comment by davidmarkclements** [comment]
I've released a patch update which locks the changes to Node 10 - the hack of using the `Number` constructor to flatten strings works in Node 8 but not in Node 10. So rather than create unintended issues in 8, let's move forward with 10.

However, if you get the chance, it would still be useful if you (both @nilesh-parab and @WarmVissarutRonaldoDude) could provide more details. For instance, are promises async/await involved anywhere? And what frameworks etc.

**Comment by nilesh-parab** [comment]
@davidmarkclements thank you for quickly jumping on this.

I am facing the issue in my app which is running on Meteor 1.5.1 that uses node 4.8.4 internally (We are working on the upgrade to latest Meteor that uses Node 8.11.1).

I was seeing this error on our app intermittently exactly like @WarmVissarutRonaldoDude noted. So as a quickfix we commented the pino logger statements to stabilize the app.

When I reported this issue, I created a test app to check & was using Node 8.11.1. Today I downloaded more 2 node versions (8.11.2 & 10.0.0) & tested the [old code commit](https://github.com/davidmarkclements/flatstr/commit/be4a7f3b1133cd1748bc292891fb761dd8e94870#diff-168726dbe96b3ce427e7fedce31bb0bc). I am getting the same output as before even for node 10 or even I may be executing it the wrong way.

I have created a [Gist](https://gist.github.com/nilesh-parab/bc9abc69e9b1366b33f14b93ecde469b) for you with the code that I am running.

Thanks,
Nilesh

**Comment by WarmVissarutRonaldoDude** [comment]
Hi @davidmarkclements 

More informations from my side

1. Using PM2 running as cluster.
2. Using original Pino lib.
3. Running with Node 6.9.4 (btw try with 8.x.x and 10.x.x already) running as server side which using Koa. 
4. Yes we has uncaughtException and we can catch it when error from calling write (info) with `pino`
5. For OS test running on OS X 10.12.4 and Ubuntu 14.04.2 LTS

Hope it can help :)

**Comment by mcollina** [comment]
It would help having an example of an application crashing.

**Comment by nilesh-parab** [comment]
@davidmarkclements @mcollina was the gist I mentioned helpful for replicating the issue?

**Comment by mcollina** [comment]
No, that was expectes behavior.

**Comment by nilesh-parab** [comment]
@mcollina I had also tried with Node 10.0.0 it produced the same output. The patch was supposed to work with 10.0.0.
I am running the test on Window 10.

**Comment by davidmarkclements** [comment]
@nilesh-parab - is it happening on 8 with the latest flatstr or only on 10?

**Comment by nilesh-parab** [comment]
I had tested the code in this [commit](https://github.com/davidmarkclements/flatstr/commit/be4a7f3b1133cd1748bc292891fb761dd8e94870#diff-168726dbe96b3ce427e7fedce31bb0bc) which is not locked to Node 10.

I got the same error with all 3 Node 8.11.1, 8.11.2 & 10.0.0 versions I tried. I have pasted the output in gist [here](https://gist.github.com/nilesh-parab/bc9abc69e9b1366b33f14b93ecde469b#file-readme-md).

The issue on our production app was inconsistent but always bubbled up from the same place @WarmVissarutRonaldoDude mentioned.

**Comment by davidmarkclements** [comment]
@nilesh-parab Your gist output is logging expected behaviour - are you able to provide a full example?

**Comment by nilesh-parab** [comment]
@davidmarkclements since the issue was occurring intermittently I would not be able to provide a full example. But here is the exact trace of the error we encountered for first time:
`
2018-05-31T08:30:37.378715+00:00 app[web.2]: SyntaxError: Unexpected token %
2018-05-31T08:30:37.378728+00:00 app[web.2]: at EventEmitter.pinoWrite (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/pino/pino.js:222:18)
2018-05-31T08:30:37.378734+00:00 app[web.2]: at EventEmitter.LOG (/app/.meteor/heroku_build/app/programs/server/npm/node_modules/pino/lib/tools.js:93:10)
2018-05-31T08:30:37.378737+00:00 app[web.2]: at cacheAnalysis (packages/ssrwpo:ssr/server/steps/cacheAnalysis.js:22:10)
2018-05-31T08:30:37.378738+00:00 app[web.2]: at callback (packages/ssrwpo:ssr/server/createRouter.js:110:7)
2018-05-31T08:30:37.378740+00:00 app[web.2]: at packages/ssrwpo:ssr/server/createRouter.js:123:7
`
I will try to create an example with pino in a standalone app & keep you updated.

**Comment by davidmarkclements** [comment]
Thanks @nilesh-parab - to be clear you're now safe to do a reinstall of pino that will fetch the latest flatstr patch - which will prevent this error from happening in 8 and below using because of the version detection

**Comment by trxcllnt** [comment]
seems like this is also an issue in node v12.0.0

**Comment by mcollina** [comment]
I cannot reproduce on node 12.0.0. Likely it’s a new issue as this was fixed long ago. Would you mind opening a new one and providing a repro?

**Comment by JustinTRoss** [comment]
I'm still getting this issue in Node 10.15.0.

`    "pino": "^5.11.1",`

It's stopping execution of the request, but isn't crashing server.

Below is the log from the error:

```
2019-05-01T02:27:26.142883+00:00 heroku[router]: at=info method=OPTIONS path="/graphql" host=xxxxx.xxxxx.xxxxx request_id=1307a700-f9c9-4f46-a241-110ed9d4524e fwd="70.95.201.64" dyno=web.1 connect=3ms service=2ms status=500 bytes=614 protocol=https
2019-05-01T02:27:26.140119+00:00 app[web.1]: SyntaxError: Unexpected token %
2019-05-01T02:27:26.140136+00:00 app[web.1]: at Pino.write (/app/node_modules/pino/lib/proto.js:110:21)
2019-05-01T02:27:26.140139+00:00 app[web.1]: at Pino.LOG [as info] (/app/node_modules/pino/lib/tools.js:35:21)
2019-05-01T02:27:26.140140+00:00 app[web.1]: at PinoLogger.info (/app/dist/application/logging/PinoLogger.js:42:19)
2019-05-01T02:27:26.140142+00:00 app[web.1]: at RequestLoggerMiddleware.handle (/app/dist/interfaces/middlewares/RequestLoggerMiddleware.js:7:25)
2019-05-01T02:27:26.140147+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2019-05-01T02:27:26.140149+00:00 app[web.1]: at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
2019-05-01T02:27:26.140150+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:284:7
2019-05-01T02:27:26.140152+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2019-05-01T02:27:26.140153+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2019-05-01T02:27:26.140154+00:00 app[web.1]: at ResolveJwtToUserMiddleware.handle (/app/dist/interfaces/middlewares/ResolveJwtToUserMiddleware.js:24:24)
```

Pino.write @ `/app/node_modules/pino/lib/proto.js:110:21`:

```
function write (obj, msg, num) {
  const t = this[timeSym]()
  const s = this[asJsonSym](obj, msg, num, t)
  const stream = this[streamSym]
  if (stream[needsMetadataGsym] === true) {
    stream.lastLevel = num
    stream.lastMsg = msg
    stream.lastObj = obj
    stream.lastTime = t.slice(8)
    stream.lastLogger = this // for child loggers
  }
  if (stream instanceof SonicBoom) stream.write(s)
  else stream.write(flatstr(s)) // Error at flatstr on this line.
}
```

**Comment by mcollina** [comment]
what’s the version of flatstr in your package-lock.json? Have you updated your dependencies?
Can you reproduce this issue reliably and upload an example?

Thanks!

**Comment by JustinTRoss** [comment]
I am unable to reproduce reliably. I haven't updated to pino 5.12 yet. Here's pino snippet from package-lock:

```
    "pino": {
      "version": "5.11.1",
      "resolved": "https://registry.npmjs.org/pino/-/pino-5.11.1.tgz",
      "integrity": "sha512-NIua0mGb9Adknq35ONvQmvh93LCUVUjp2+1q1EcvIkJmpJnSd3E5rHVKlKNjzMXFl/z3fI+QA0xXCjPEKNiLvQ==",
      "requires": {
        "fast-redact": "^1.4.2",
        "fast-safe-stringify": "^2.0.6",
        "flatstr": "^1.0.9",
        "pino-std-serializers": "^2.3.0",
        "quick-format-unescaped": "^3.0.0",
        "sonic-boom": "^0.7.1"
      }
    },
```

**Comment by mcollina** [comment]
I’m interested in the flatstr part, not the pino part.

**Comment by JustinTRoss** [comment]
flatstr was 1.0.9.

Edit:

In case whole shebang is useful for you:
```
    "flatstr": {
      "version": "1.0.9",
      "resolved": "https://registry.npmjs.org/flatstr/-/flatstr-1.0.9.tgz",
      "integrity": "sha512-qFlJnOBWDfIaunF54/lBqNKmXOI0HqNhu+mHkLmbaBXlS71PUd9OjFOdyevHt/aHoHB1+eW7eKHgRKOG5aHSpw=="
    },
```

I have updated dependencies and am now at 1.0.10. I'll update if the issue resurfaces.

**Comment by mcollina** [comment]
Thanks!

**Comment by ptrcnull** [comment]
Still happens on 1.0.10, Node 12.1.0, running on Docker (Alpine Linux ~~, maybe that's the problem?~~)  
EDIT: yeah, that's probably Alpine/Docker, because I can run it on macOS and Ubuntu on the same setup with no problems

For me it's in Fastify:
```
Unexpected token %
SyntaxError: Unexpected token %
    at preserializeHookEnd (fastify/lib/reply.js:245:3)
    at preserializeHook (fastify/lib/reply.js:234:5)
    at _Reply.Reply.send (fastify/lib/reply.js:133:5)
    at Object.<anonymous> (/app/dist/api/index.js:41:15)
    at preHandlerCallback (fastify/lib/handleRequest.js:112:30)
    at next (fastify/lib/hooks.js:66:7)
    at Object.<anonymous> (/app/dist/api/index.js:24:13)
    at hookIterator (fastify/lib/hooks.js:124:10)
    at next (fastify/lib/hooks.js:70:20)
    at hookRunner (fastify/lib/hooks.js:84:3)
```
api/index.js:41:
```
reply.send({ info: 'it works' })
```

**Comment by mcollina** [comment]
Are you transpiling your code by any chance?

**Comment by ptrcnull** [comment]
Yup, I've written my app in TypeScript and I'm running the transpiled version in Docker

**Comment by davidmarkclements** [comment]
ok.. without being able to reproduce here's another attempt: 

~~https://github.com/davidmarkclements/flatstr/commit/1b63eebba9e88c7d21d1643055e22aa830b3e12b~~ (edit, wrong commit):  https://github.com/davidmarkclements/flatstr/commit/4306e6586453d4d76b3aae309a484be70e7e62d5

published as 1.0.11 

This fix doesn't affect the benchmarks (since try/catch is optimized now), but would you mind

1. confirming whether this works for your setup
2. whether it affects any benchmarks you have (or, perhaps you could check whether the it's successfully passing through the try block after the first few calls)

**Comment by ptrcnull** [comment]
It works, thanks!

**Comment by ptrcnull** [comment]
By the way, what's the point of the _flatstr in the catch clause if in the end `s` is returned?

**Comment by JustinTRoss** [comment]
Just fyi - 1.0.10 errors on Node 12.2.0.

Updating to 1.0.11 and will let you know if it happens again.
