### ISSUE TITLE
undefined:3 return typeof s === "string" ? %FlattenString(s) : s

### ISSUE THREAD

**Issue by perljusback** [davidmarkclements/flatstr#7]
I'm getting this error when testing out node v12.0.0 with fastify and pino logging.

![image](https://user-images.githubusercontent.com/3188312/56949903-72341c80-6b34-11e9-8bbf-d0e7a55b9248.png)

Node Version: v12.0.0
OS: Windows 10
Fastify version: 2.3.0

If i remove the logging everything works fine, if there's anything else i can provide please let me know.

**Comment by mcollina** [comment]
I have not been able to reproduce on Mac or Linux, and all Fastify tests pass on Windows. Would you mind including a repro?

**Comment by perljusback** [comment]
I cant share the repo i'm using, but I managed to reproduce it with a newly created Nuxt with fastify as Server, so maybe it's a nuxt + fastify combo that creates this issue somehow

**Comment by davidmarkclements** [comment]
Would you mind setting up this scenario and sharing it?

**Comment by perljusback** [comment]
[Repo](https://github.com/perljusback/nuxt-fastify-flatstr)

I've uploaded the one I used to verify it with, i do notice that sometimes it works and others it doesn't trying to figure out exactly what changes between those instances.

**Comment by davidmarkclements** [comment]
this should fix it: https://github.com/davidmarkclements/flatstr/commit/689e327f8ad82f4d9c017185fb064f791beecf0a

flatstr 1.0.10 published - if you simply rm node_modules and reinstall it should solve it

there's a deeply technical explanation, the details of which I'm only hazily aware of - but suffice it to say, it's most likely due to an odd V8 bug around functions shared address spaces and V8 flag state handling in C++ layer.

**Comment by davidmarkclements** [comment]
closing - feel free to reopen if for some reason it doesn't solve it

**Comment by perljusback** [comment]
I'm still getting the same error even after upgrading to the new version.

I've done some additional tests:

- Building seperatly and then running the server in production mode doesn't reproduce the error
- Installed pino on a node grpc service and i couldn't reproduce the error even in development mode

So it seems like this error only occurs when nuxt builds and then the server starts in the same process for the lack of a better word.

Thanks for looking into this if I find any solution I'll come back.

**Comment by davidmarkclements** [comment]
that's odd. since it's an edge case, trying add `--allow-native-syntax` flag to any node processes that get started up - that should eliminate the failure

**Comment by endymonium** [comment]
I'm seeing the same error, node with fastify + pino (dev env with nodemon). It seems to happen randomly, but I've got one flow where it happens everytime (can't share repo I'm afraid).

Latest version (1.0.11) didn't help, --allow-native**s**-syntax fixes it though

``` 
SyntaxError: Unexpected token %
    at Pino.write (...\node_modules\pino\lib\proto.js:137:21)
    at Pino.LOG (...\node_modules\pino\lib\tools.js:35:26)
```

**Comment by davidmarkclements** [comment]
No need to expose your proprietary code but if you can provide an isolated
reproducible case  I’ll look into it

**Comment by mudivili** [comment]
The same issue in my project as well. Raised an issue in [fastify](https://github.com/fastify/fastify/issues/1758)(May be I must have reported here).

Similar with others, the issue happens randomly. So, not able to provide with reproducible code. Sorry about that. In my case, the stringified JSON string is passed from fastify to flatstr. 

Curious, Why is this issue happening? <strike>What is the purpose of this module?</strike>(Read the README.md).

For what it's worth, in my case, fastify is using flatstr@v1.0.9

**Comment by davidmarkclements** [comment]
flatstr@1.0.12 will solves this problem, you just need to make sure the dep is updated

As long as fastify hasn't locked to that specific version, this should work:

```
rm -fr node_modules
npm install
```

**Comment by mcollina** [comment]
also  `rm package-lock.json`. this is all the result of package-lock.
